version: '3'
# https://taskfile.dev

shopt: [globstar]

dotenv: [ ".env" ]

includes:
  build: ./taskfiles/build.yml
  test: ./taskfiles/test.yml
  odin: ./taskfiles/odin.yml
  ols: ./taskfiles/ols.yml

tasks:
  init:
    deps: [odin:pull, ols:pull]
    desc: "Download and (if necessary) build all dependencies."
    cmds:
      - task: odin:init-linux
      - task: ols:init-linux
