version: '3'
# https://taskfile.dev

shopt: [globstar]

includes:
  build: ./taskfiles/build.yml
  test: ./taskfiles/test.yml
  odin: ./taskfiles/odin.yml
  ols: ./taskfiles/ols.yml

tasks:
  init:
    desc: "Download and (if necessary) build all dependencies."
    cmds:
      - task: odin:pull
      - task: odin:init-linux
      - task: ols:pull
      - task: ols:init-linux
