version: '3'
# https://taskfile.dev

shopt: [globstar]

dotenv: [ ".env" ]

includes:
  build: ./taskfiles/build.yml
  test: ./taskfiles/test.yml
  odin: ./taskfiles/odin.yml
  ols: ./taskfiles/ols.yml

tasks:
  pull:
    desc: "Pull all dependencies."
    cmds:
      - task: odin:pull
      - task: ols:pull

  init:
    deps: [pull]
    desc: "Build all dependencies."
    cmds:
      - task: odin:init-linux
      - task: ols:init-linux
